name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy Via SSH
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /app/userapi
          git pull origin main
          docker stop basicexpress || true
          docker rm basicexpress || true
          docker build -t basicexpress .
          docker run -d \
              -p 5000:5000 \
              --restart always \
              --name basicexpress \
              basicexpress